### ISSUE TITLE
Versioning Issue

### ISSUE THREAD

**Issue by msauberPrincipal** [pantheon-systems/drops-8-scaffolding#1]
I'm running into an install error.  My repo is attempting to install v8.6.14; however, upon looking at the most recent release, it looks like this was incorrectly labelled v8.5.14.

**Comment by greg-1-anderson** [comment]
It is true that the order of commits in the `master` branch of this repository is not correct. The script that builds this repo assumes that the Semver tags in the Drupal 8.x repository are created in a monotonically increasing order. However, drupal.org started releasing security fixes for older versions of Drupal, e.g. 8.5.15, released along with 8.6.16.  Every commit on the master branch takes all of the files from the corresponding version of Drupal 8, and tags it with the same version number. So, even though 8.5.14 appears on the master branch after 8.6.14, if you compare the files in these tags with what is in the equivalently-versioned main Drupal repository, you will find that the files contained therein are correct.
