### ISSUE TITLE
Missing 8.7.14 tag

### ISSUE THREAD

**Issue by ccjjmartin** [pantheon-systems/drops-8-scaffolding#10]
This is a security release

**Comment by ccjjmartin** [comment]
@greg-1-anderson This is a security release, so hoping it comes out soon.

**Comment by greg-1-anderson** [comment]
This will be available today.

**Comment by greg-1-anderson** [comment]
Also, for all of those who are here looking for this tag: I would recommend you switch from drupal-composer/drupal-scaffold to the better tool, drupal/core-composer-scaffold. The later tool is part of Drupal 8.8.0+, but you can still install it to your Composer-managed site and use it with earlier versions of Drupal.  See pantheon-systems/example-drops-8-composer for an example of how to configure and use the core-composer-scaffold component. Basically, you will stop using this repo and start using pantheon-systems/drupal-integrations. That repo does not need new tags with each Drupal release.

We still intend to maintain drops-8-scaffolding, but several concurrent operational problems have caused us to fall outside of our SLA for a couple of derivative components, like the 8.7.14 tag on this repo. Thank you for your patience.

**Comment by ccjjmartin** [comment]
@greg-1-anderson Thank you for continuing to maintain this repo.

**Comment by laura-zimmerman** [comment]
I may have gotten this alternate approach working for 8.7, by replacing drupal-composer/drupal-scaffold with drupal/core-composer-scaffold and also updating the "scripts" and "extra" sections in composer.json.

It was necessary to remove vendor/drupal-composer/drupal-scaffold and docroot/drush/contrib (now in drush/Commands).

**Comment by greg-1-anderson** [comment]
This tag is available now.  The automation for this repository has been improved; the previous-minor tags will show up sooner after the next security release.

This project will be maintained through Drupal 8.9.9999999. There will be no ^9 tags added here; please plan on upgrading to drupal/core-composer-scaffold before upgrading to Drupal 9.
