### ISSUE TITLE
Update scaffolding for Drupal Core 8.7.5

### ISSUE THREAD

**Issue by philltran** [pantheon-systems/drops-8-scaffolding#3]
I was not able to update my example-drops-8-composer based site becuase of error 

`  [Exception]                                                                                                                             
  Failed to download:                                                                                                                     
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.7.5/.gitattributes                                             
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.7.5/.ht.router.php                                             
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.7.5/index.php                                                  
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.7.5/robots.txt                                                 
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.7.5/sites/default/default.services.yml                         
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.7.5/sites/default/default.settings.php                         
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.7.5/sites/development.services.yml                             
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.7.5/sites/example.settings.local.php                           
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.7.5/sites/example.sites.php                                    
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.7.5/update.php                                                 
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.7.5/sites/default/default.services.pantheon.preproduction.yml  
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.7.5/sites/default/settings.pantheon.php                                                                                                                                                   `

Is there something I can do to help create that release?

Thanks!

**Comment by philltran** [comment]
Nevermind... I am too slow at posting the issue. Looks like you added a release.

**Comment by greg-1-anderson** [comment]
This project is updated automatically via the CI scripts that update Drupal.

**Comment by philltran** [comment]
That’s good to know. Thanks for clueing me in.

**Comment by greg-1-anderson** [comment]
Also, improvements from the Composer in Core Drupal Initiative will hopefully allow us to make improvements here in the Drupal 8.8.0 timeframe that will eliminate the window just after releases where our Pantheon Composer builds fail.
