### ISSUE TITLE
Missing 8.7.7 scaffolding tag

### ISSUE THREAD

**Issue by davereid** [pantheon-systems/drops-8-scaffolding#4]
According to https://github.com/pantheon-systems/drops-8-scaffolding/issues/3 this should be updated by CI script automatically, but I'm wondering if https://www.drupal.org/project/drupal/issues/3078671 would possibly be causing CI failures preventing the build from happening.

**Comment by davereid** [comment]
I can't see what the current failure is with https://dashboard.guardrails.io/default/gh/pantheon-systems/drops-8-scaffolding/9776af2da304afd55224da24f9f6d9c2243f20a3?type=branch

**Comment by greg-1-anderson** [comment]
Just starting my day. I am not sure yet whether #3078671  is preventing the scaffolding tag from being created or not. Having the 8.7.7 scaffolding tag is necessary but insufficient for upgrading a Pantheon Drupal site; it will also be necessary to work around the problem in your top-level composer.json file, unless we either wait for the upstream fix or make a persistent workaround (e.g. fork the upstream).

The Composer In Core initiative meeting is starting in a few minutes; let's see what folks say there.

**Comment by davereid** [comment]
It's available now!
