### ISSUE TITLE
Lando failing due to source files not found

### ISSUE THREAD

**Issue by trittgers-principal** [pantheon-systems/drops-8-scaffolding#6]
We are currently unable to run our Pantheon site locally due to these download failures:

> DrupalComposer\DrupalScaffold\Plugin::scaffold
  - Downloading 0/12: https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.0/robots.txt (failed)
  - Downloading 0/12: https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.0/sites/default/default.settings.php (failed)
  - Downloading 0/12: https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.0/update.php (failed)
  - Downloading 0/12: https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.0/sites/default/settings.pantheon.php (failed)
  - Downloading 0/12: https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.0/sites/default/default.services.pantheon.preproduction.yml (failed)
  - Downloading 0/12: https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.0/sites/example.sites.php (failed)
  - Downloading 0/12: https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.0/sites/default/default.services.yml (failed)
  - Downloading 0/12: https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.0/index.php (failed)
  - Downloading 0/12: https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.0/.ht.router.php (failed)
  - Downloading 0/12: https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.0/sites/development.services.yml (failed)
  - Downloading 0/12: https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.0/.gitattributes (failed)
  - Downloading 0/12: https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.0/sites/example.settings.local.php (failed)

  - Has failed with the last source: https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/{version}/{path}

Script DrupalComposer\DrupalScaffold\Plugin::scaffold handling the drupal-scaffold event terminated with an exception

**Comment by trittgers-principal** [comment]
Any updates here?

**Comment by greg-1-anderson** [comment]
The 8.8.0 tag exists here now, which should clear up the problem above.

**Comment by trittgers-principal** [comment]
I am now able to get the 8.8.0 files, but when I install with them I get this when trying to hit the site: Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pantheon.path_alias' doesn't exist: SELECT 1 AS expression FROM {path_alias} base_table WHERE (base_table.status = :db_condition_placeholder_0) AND (base_table.path LIKE :db_condition_placeholder_1 ESCAPE '\\') LIMIT 1 OFFSET 0; Array ( [:db_condition_placeholder_0] => 1 [:db_condition_placeholder_1] => /home% ) in Drupal\Core\Path\AliasRepository->pathHasMatchingAlias() (line 111 of core/lib/Drupal/Core/Path/AliasRepository.php).

**Comment by greg-1-anderson** [comment]
I've seen folks complaining about that elsewhere. Apparently, if you start over (grab your live database) and then update pathauto first, then update the rest, that error goes away.

Sorry, I've only heard about this anecdotally - I do not have specific instructions.

**Comment by ccjjmartin** [comment]
@trittgers-principal As part of the 8.8.x upgrades you have to update pathauto to 1.6 or above (I would recommend 1.6.0 as the 1.7.0 is not recommended since it accidentally broke stuff).  You will have to run `drush updb` as part of the process.  I would say this is not a problem with this repository and the issue should be closed.

**Comment by greg-1-anderson** [comment]
Closing.
