### ISSUE TITLE
Missing 8.8.6 tag 

### ISSUE THREAD

**Issue by peterfarrow-terc** [pantheon-systems/drops-8-scaffolding#9]
Missing 8.8.6 tag per: 
https://github.com/pantheon-systems/drops-8-scaffolding

When building a multidev, the following errors are thrown:

- Has failed with the last source: https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/{version}/{path}
 

 
Script DrupalComposer\DrupalScaffold\Plugin::scaffold handling the drupal-scaffold event terminated with an exception
 

 
                                                                                                                                          
 
  [Exception]                                                                                                                             
 
  Failed to download:                                                                                                                     
 
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/index.php                                                  
 
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/sites/default/default.services.yml                         
 
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/robots.txt                                                 
 
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/sites/default/default.settings.php                         
 
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/update.php                                                 
 
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/sites/example.sites.php                                    
 
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/sites/default/settings.pantheon.php                        
 
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/sites/default/default.services.pantheon.preproduction.yml  
 
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/.ht.router.php                                             
 
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/.gitattributes                                             
 
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/sites/example.settings.local.php                           
 
  https://raw.githubusercontent.com/pantheon-systems/drops-8-scaffolding/8.8.6/sites/development.services.yml

**Comment by laura-zimmerman** [comment]
Rather than open a nearly identical issue - missing 8.7.14 tag also, with the same failures on `composer update`.

**Comment by ccjjmartin** [comment]
The 8.8.6 tag exists now, 8.7.14 is still missing

**Comment by ccjjmartin** [comment]
Created issue #10 to get attention to it, this one can be closed.

**Comment by greg-1-anderson** [comment]
Yes, 8.8.6 is available.
